export interface MarketItem {
  id: string;
  shopName: string;
  ownerName: string;
  sellerRating: number;
  verified: boolean;
  itemName: string;
  quantity: string;
  category: string;
  expiryDate: string;
  daysUntilExpiry: number;
  askingPrice: number;
  willingToSwapFor?: string;
  timeOnPlatform: string;
  distance: number;
  image: string;
  condition: 'New' | 'Good' | 'Fair';
  listingType: 'swap' | 'sell' | 'both';
}

export const mockMarketItems: MarketItem[] = [
  {
    id: '1',
    shopName: 'Patel Traders',
    ownerName: 'Ramesh Patel',
    sellerRating: 4.8,
    verified: true,
    itemName: 'Britannia Good Day Biscuits - Bulk Pack',
    quantity: '48 packets x 250g (12kg total)',
    category: 'Food',
    expiryDate: '2024-12-20',
    daysUntilExpiry: 8,
    askingPrice: 2400,
    willingToSwapFor: 'Fortune Sunflower Oil, Tata Tea Premium',
    timeOnPlatform: '2 hours ago',
    distance: 0.5,
    image: 'https://images.unsplash.com/photo-1762417582386-611a7f85ea63?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwYWNrYWdlZCUyMHNuYWNrcyUyMGZvb2R8ZW58MXx8fHwxNzY1NTMwOTMyfDA&ixlib=rb-4.1.0&q=80&w=400',
    condition: 'Good',
    listingType: 'both',
  },
  {
    id: '2',
    shopName: 'Kumar General Store',
    ownerName: 'Suresh Kumar',
    sellerRating: 4.5,
    verified: true,
    itemName: 'Maggi 2-Minute Noodles Masala',
    quantity: '200 packets x 70g',
    category: 'Food',
    expiryDate: '2024-12-25',
    daysUntilExpiry: 13,
    askingPrice: 3600,
    willingToSwapFor: 'Haldiram Chips, Parle Monaco Biscuits',
    timeOnPlatform: '5 hours ago',
    distance: 1.2,
    image: 'https://images.unsplash.com/photo-1762417582386-611a7f85ea63?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwYWNrYWdlZCUyMHNuYWNrcyUyMGZvb2R8ZW58MXx8fHwxNzY1NTMwOTMyfDA&ixlib=rb-4.1.0&q=80&w=400',
    condition: 'Good',
    listingType: 'both',
  },
  {
    id: '3',
    shopName: 'Shah Enterprises',
    ownerName: 'Mukesh Shah',
    sellerRating: 4.9,
    verified: true,
    itemName: 'Tata Salt - Iodized (Vacuum Pack)',
    quantity: '50 bags x 1kg each',
    category: 'FMCG',
    expiryDate: '2025-06-30',
    daysUntilExpiry: 200,
    askingPrice: 4500,
    timeOnPlatform: '1 day ago',
    distance: 0.8,
    image: 'https://images.unsplash.com/photo-1764795850260-ebde75c8a39d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxyZXRhaWwlMjBwcm9kdWN0cyUyMGludmVudG9yeXxlbnwxfHx8fDE3NjU1MzA5MzJ8MA&ixlib=rb-4.1.0&q=80&w=400',
    condition: 'New',
    listingType: 'sell',
  },
  {
    id: '4',
    shopName: 'Gupta Medical & General',
    ownerName: 'Rajesh Gupta',
    sellerRating: 4.7,
    verified: true,
    itemName: 'Dettol Instant Hand Sanitizer 500ml',
    quantity: '60 bottles',
    category: 'Pharma',
    expiryDate: '2024-12-18',
    daysUntilExpiry: 6,
    askingPrice: 5200,
    willingToSwapFor: 'Surgical Face Masks, Cotton Bandages',
    timeOnPlatform: '3 hours ago',
    distance: 1.5,
    image: 'https://images.unsplash.com/photo-1580870069867-74c57ee1bb07?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb3NtZXRpYyUyMHByb2R1Y3RzfGVufDF8fHx8MTc2NTUzMDkzMnww&ixlib=rb-4.1.0&q=80&w=400',
    condition: 'Good',
    listingType: 'both',
  },
  {
    id: '5',
    shopName: 'Verma Kirana Store',
    ownerName: 'Amit Verma',
    sellerRating: 4.3,
    verified: false,
    itemName: 'Lays Potato Chips - Variety Pack',
    quantity: '120 packets (assorted flavors)',
    category: 'Food',
    expiryDate: '2024-12-22',
    daysUntilExpiry: 10,
    askingPrice: 2800,
    willingToSwapFor: 'Kurkure, Uncle Chips, Bingo',
    timeOnPlatform: '8 hours ago',
    distance: 2.1,
    image: 'https://images.unsplash.com/photo-1764795850260-ebde75c8a39d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxyZXRhaWwlMjBwcm9kdWN0cyUyMGludmVudG9yeXxlbnwxfHx8fDE3NjU1MzA5MzJ8MA&ixlib=rb-4.1.0&q=80&w=400',
    condition: 'Good',
    listingType: 'swap',
  },
  {
    id: '6',
    shopName: 'Singh Electronics',
    ownerName: 'Harpreet Singh',
    sellerRating: 4.6,
    verified: true,
    itemName: 'USB Type-C Charging Cables (1m)',
    quantity: '100 pieces - Fast Charging',
    category: 'Electronics',
    expiryDate: '2026-12-31',
    daysUntilExpiry: 749,
    askingPrice: 3200,
    timeOnPlatform: '2 days ago',
    distance: 1.8,
    image: 'https://images.unsplash.com/photo-1609081219090-a6d81d3085bf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxlbGVjdHJvbmljJTIwZ2FkZ2V0c3xlbnwxfHx8fDE3NjU0NDc0NTV8MA&ixlib=rb-4.1.0&q=80&w=400',
    condition: 'New',
    listingType: 'sell',
  },
  {
    id: '7',
    shopName: 'Rao Cosmetics Corner',
    ownerName: 'Lakshmi Rao',
    sellerRating: 4.8,
    verified: true,
    itemName: 'Lakme 9to5 Lipstick Collection',
    quantity: '36 pieces (12 shades x 3 each)',
    category: 'Cosmetics',
    expiryDate: '2025-01-15',
    daysUntilExpiry: 34,
    askingPrice: 4800,
    willingToSwapFor: 'Lakme Nail Polish, Maybelline Products',
    timeOnPlatform: '4 hours ago',
    distance: 0.9,
    image: 'https://images.unsplash.com/photo-1580870069867-74c57ee1bb07?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb3NtZXRpYyUyMHByb2R1Y3RzfGVufDF8fHx8MTc2NTUzMDkzMnww&ixlib=rb-4.1.0&q=80&w=400',
    condition: 'Good',
    listingType: 'both',
  },
  {
    id: '8',
    shopName: 'Mehta Grocery Mart',
    ownerName: 'Ashok Mehta',
    sellerRating: 4.4,
    verified: true,
    itemName: 'Parle-G Gold Biscuits - Economy Pack',
    quantity: '72 packets x 200g',
    category: 'Food',
    expiryDate: '2024-12-28',
    daysUntilExpiry: 16,
    askingPrice: 1800,
    willingToSwapFor: 'Cadbury Dairy Milk, Nestle Munch',
    timeOnPlatform: '6 hours ago',
    distance: 1.4,
    image: 'https://images.unsplash.com/photo-1762417582386-611a7f85ea63?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwYWNrYWdlZCUyMHNuYWNrcyUyMGZvb2R8ZW58MXx8fHwxNzY1NTMwOTMyfDA&ixlib=rb-4.1.0&q=80&w=400',
    condition: 'Good',
    listingType: 'swap',
  },
  {
    id: '9',
    shopName: 'Chopra Departmental Store',
    ownerName: 'Vikram Chopra',
    sellerRating: 4.9,
    verified: true,
    itemName: 'Amul Butter - Salted (100g)',
    quantity: '80 packs',
    category: 'Food',
    expiryDate: '2024-12-19',
    daysUntilExpiry: 7,
    askingPrice: 3200,
    willingToSwapFor: 'Amul Cheese, Mother Dairy Paneer',
    timeOnPlatform: '1 hour ago',
    distance: 0.6,
    image: 'https://images.unsplash.com/photo-1764795850260-ebde75c8a39d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxyZXRhaWwlMjBwcm9kdWN0cyUyMGludmVudG9yeXxlbnwxfHx8fDE3NjU1MzA5MzJ8MA&ixlib=rb-4.1.0&q=80&w=400',
    condition: 'Good',
    listingType: 'both',
  },
  {
    id: '10',
    shopName: 'Desai Super Market',
    ownerName: 'Kiran Desai',
    sellerRating: 4.6,
    verified: true,
    itemName: 'Colgate MaxFresh Toothpaste 150g',
    quantity: '50 tubes',
    category: 'FMCG',
    expiryDate: '2025-03-30',
    daysUntilExpiry: 108,
    askingPrice: 2250,
    timeOnPlatform: '12 hours ago',
    distance: 1.1,
    image: 'https://images.unsplash.com/photo-1580870069867-74c57ee1bb07?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb3NtZXRpYyUyMHByb2R1Y3RzfGVufDF8fHx8MTc2NTUzMDkzMnww&ixlib=rb-4.1.0&q=80&w=400',
    condition: 'New',
    listingType: 'sell',
  },
  {
    id: '11',
    shopName: 'Joshi Provision Store',
    ownerName: 'Prakash Joshi',
    sellerRating: 4.2,
    verified: false,
    itemName: 'Aashirvaad Whole Wheat Atta 5kg',
    quantity: '40 bags',
    category: 'Food',
    expiryDate: '2025-02-28',
    daysUntilExpiry: 78,
    askingPrice: 6400,
    timeOnPlatform: '1 day ago',
    distance: 2.3,
    image: 'https://images.unsplash.com/photo-1764795850260-ebde75c8a39d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxyZXRhaWwlMjBwcm9kdWN0cyUyMGludmVudG9yeXxlbnwxfHx8fDE3NjU1MzA5MzJ8MA&ixlib=rb-4.1.0&q=80&w=400',
    condition: 'New',
    listingType: 'sell',
  },
  {
    id: '12',
    shopName: 'Reddy Medical Store',
    ownerName: 'Srinivas Reddy',
    sellerRating: 4.7,
    verified: true,
    itemName: 'Vicks VapoRub 50ml Jars',
    quantity: '45 jars',
    category: 'Pharma',
    expiryDate: '2025-04-20',
    daysUntilExpiry: 129,
    askingPrice: 2700,
    willingToSwapFor: 'Zandu Balm, Moov Spray',
    timeOnPlatform: '9 hours ago',
    distance: 1.7,
    image: 'https://images.unsplash.com/photo-1580870069867-74c57ee1bb07?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb3NtZXRpYyUyMHByb2R1Y3RzfGVufDF8fHx8MTc2NTUzMDkzMnww&ixlib=rb-4.1.0&q=80&w=400',
    condition: 'Good',
    listingType: 'both',
  },
];

export const mockWantedItems = [
  {
    id: 'w1',
    shopName: 'Sharma Retail Hub',
    buyerName: 'Dinesh Sharma',
    itemWanted: 'Horlicks Health Drink - 1kg Jars',
    quantity: '25-30 jars (any flavor)',
    willingToPay: 4500,
    willingToExchange: 'Bournvita 1kg, Complan 500g, Boost 1kg',
    timePosted: '1 hour ago',
    distance: 0.7,
    verified: true,
  },
  {
    id: 'w2',
    shopName: 'Khan Departmental Store',
    buyerName: 'Aslam Khan',
    itemWanted: 'Dove Soap Bars (Original)',
    quantity: '50-60 bars (75g or 100g)',
    willingToPay: 2800,
    willingToExchange: 'Lux, Lifebuoy, Pears Soap',
    timePosted: '3 hours ago',
    distance: 1.1,
    verified: true,
  },
  {
    id: 'w3',
    shopName: 'Joshi Kirana Bhandar',
    buyerName: 'Manoj Joshi',
    itemWanted: 'Aashirvaad Atta (Whole Wheat Flour)',
    quantity: '100-150 kg (any pack size)',
    willingToPay: 4200,
    timePosted: '5 hours ago',
    distance: 1.8,
    verified: false,
  },
  {
    id: 'w4',
    shopName: 'Nair Supermarket',
    buyerName: 'Rajesh Nair',
    itemWanted: 'Haldiram Namkeen - Bhujia/Aloo Bhujia',
    quantity: '30-40 packets (200g or 400g)',
    willingToPay: 3200,
    willingToExchange: 'Bikano Namkeen, Balaji Wafers',
    timePosted: '7 hours ago',
    distance: 0.9,
    verified: true,
  },
  {
    id: 'w5',
    shopName: 'Bansal Grocery Store',
    buyerName: 'Rohit Bansal',
    itemWanted: 'Fortune Refined Sunflower Oil 1L',
    quantity: '20-25 bottles',
    willingToPay: 2500,
    willingToExchange: 'Saffola Oil, Gemini Oil',
    timePosted: '10 hours ago',
    distance: 2.0,
    verified: true,
  },
];